spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost/mybatis-template?characterEncoding=utf-8&useSSL=false

mybatis:
    type-aliases-package: com.jhon.rain.entity
    mapper-locations: classpath:mapper/*.xml